// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyCf8CnpYjC4QTOICTc82HeT8HC9v-n4ioo',
    appId: '1:16460806860:android:90e85ec88543caf459e069',
    messagingSenderId: '16460806860',
    projectId: 'fuelbook-109d5',
    databaseURL: 'https://fuelbook-109d5-default-rtdb.firebaseio.com',
    storageBucket: 'fuelbook-109d5.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyDLZKVX6RdEGzv0hCOTLccXWJPOpWhWKlo',
    appId: '1:16460806860:ios:bde46b8b2c247ce259e069',
    messagingSenderId: '16460806860',
    projectId: 'fuelbook-109d5',
    databaseURL: 'https://fuelbook-109d5-default-rtdb.firebaseio.com',
    storageBucket: 'fuelbook-109d5.appspot.com',
    iosClientId:
        '16460806860-v8p86rmqha9c4g3f0k5o0jujjlhn6lvv.apps.googleusercontent.com',
    iosBundleId: 'com.vivek.app.fuelbook',
  );
}
